deploy:
  stage: deploy
  before_script:
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - apk add openssh-client rsync
    - eval $(ssh-agent -s)
    - cat $SSH_PRIVATE_KEY | tr -d '\r' | ssh-add -
    - cat $SSH_CONFIG > ~/.ssh/config
  only:
    - master
  tags:
    - services  
  except:
    - schedules
  script:
    - echo $HOST
    - cat $ENV_WEB > variables/.env_web
    - cat $ENV_SRV > variables/.env_srv
    - cat $ENV_DB_PSQL > variables/.env_db_pgsql
    - ssh -l work $HOST -o StrictHostKeyChecking=no "mkdir -p $CI_PROJECT_NAME/variables || true"
    - rsync -avz variables/.env_* --exclude='*.example' work@$HOST:~/$CI_PROJECT_NAME/variables/
    - cat docker-compose.yml | ssh -l work $HOST -T "cat > ~/$CI_PROJECT_NAME/docker-compose.yml"
    - ssh -l work $HOST "
        docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY &&
        cd ~/$CI_PROJECT_NAME &&
        docker-compose pull &&
        docker-compose down &&
        docker-compose up -d &&
        yes | docker system prune -a"
