version: '3.5'
services:
 zabbix-server:
  restart: always
  image: zabbix/zabbix-server-pgsql:alpine-5.0.5
  ports:
   - "10051:10051"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro
   - ./volumes/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
   - ./volumes/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
   - ./volumes/var/lib/zabbix/export:/var/lib/zabbix/export:rw
   - ./volumes/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
   - ./volumes/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
   - ./volumes/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
   - ./volumes/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
   - ./volumes/var/lib/zabbix/snmptraps:/var/lib/zabbix/snmptraps:ro
  env_file:
   - variables/.env_db_pgsql
   - variables/.env_srv
  depends_on:
   - postgres-server
  stop_grace_period: 30s
  sysctls:
   - net.ipv4.ip_local_port_range=1024 65000
   - net.ipv4.conf.all.accept_redirects=0
   - net.ipv4.conf.all.secure_redirects=0
   - net.ipv4.conf.all.send_redirects=0
  labels:
   com.zabbix.description: "Zabbix server with PostgreSQL database support"
   com.zabbix.company: "Zabbix Apptimizm"
   com.zabbix.component: "zabbix-server"
   com.zabbix.dbtype: "pgsql"
   com.zabbix.os: "alpine"

 zabbix-web-nginx-pgsql:
  restart: always
  image: zabbix/zabbix-web-nginx-pgsql:alpine-5.0.5
  ports:
   - "8081:8080"
   - "8443:8443"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro
   - ./volumes/etc/ssl/nginx:/etc/ssl/nginx:ro
   - ./volumes/usr/share/zabbix/modules/:/usr/share/zabbix/modules/:ro
  env_file:
   - variables/.env_db_pgsql
   - variables/.env_web
  depends_on:
   - postgres-server
   - zabbix-server
  healthcheck:
   test: ["CMD", "curl", "-f", "http://localhost:8080/"]
   interval: 10s
   timeout: 5s
   retries: 3
   start_period: 30s
  stop_grace_period: 10s
  sysctls:
   - net.core.somaxconn=65535

 postgres-server:
  restart: always
  image: postgres:12.8
  volumes:
   - ./volumes/var/lib/postgresql/data:/var/lib/postgresql/data:rw
   - ./volumes/backup:/backup
  env_file:
   - variables/.env_db_pgsql
  stop_grace_period: 1m
